### ISSUE TITLE
We have discovered a crash in the unsubscribe all method.

### ISSUE THREAD

**Issue by PieterJanDevolder** [jisotalo/ads-client#103]
![image](https://user-images.githubusercontent.com/67792812/217804371-e54f7146-a897-43e3-86d4-ce20743d373a.png)

**Comment by jisotalo** [comment]
Hi. 

Thanks for reporting. Does this happen every time you call it?

**Comment by PieterJanDevolder** [comment]
> Hi.
> 
> Thanks for reporting. Does this happen every time you call it?

No this happens after some time, hard to simulate this situation.

**Comment by jisotalo** [comment]
Could you provide an example code?

**Comment by PieterJanDevolder** [comment]
> Could you provide an example code?

i've sent an email

**Comment by jisotalo** [comment]
This was discussed in email with @PieterJanDevolder:

> I tried to recreate this issue and only way I could manage to do it was calling unsubcribeAll() multiple times at the same time. So another promise was already unsubscribing when the next one tried to unsubscribe again.
> 
> So one possible reason could be that you code is doing that twice or ads-client is already doing it itself as it has noticed the connection loss. The client will reconnect and unsubscribe&resubscribe automatically if connection gets lost. I definetely need to add some null-checking to the method in the future.

So the reason might be that the subscription is already deleted. There is no null check in error handler at `ads-client.js` row 1227 to see if subscription exists:
https://github.com/jisotalo/ads-client/blob/master/src/ads-client.js#L1227

There should be a check just like in unsubscribe():
https://github.com/jisotalo/ads-client/blob/master/src/ads-client.js#L1184

The original reason is still a mystery. Maybe the ads-client is reconnecting at the same time and has just unsubscribed already.

I will close this issue when the null check is added.

**Comment by jisotalo** [comment]
Fixed in 1.14.2
