### ISSUE TITLE
exported code of matlab has type MatSim.DINT

### ISSUE THREAD

**Issue by JarmoCluyse** [jisotalo/ads-client#107]
the interface communicates with matlab/simulink generated code.
We never had an issue before, 
with the new code generator if we generate a int32 it changes to this type and the package crashes with this error:

\node_modules\ads-client\src\ads-client-ads.js:956
      throw new Error(`Error: Base type ${name} not found from BaseDataTypes - If this should be found, report an issue`)

Error: Error: Base type MatSim.DINT not found from BaseDataTypes - If this should be found, report an issue

**Comment by jisotalo** [comment]
Hi @JarmoCluyse!

I had somehow missed this issue, sorry.

Could you elaborate more? Any code example? It seems that instead of the basic type `DINT` the Simulink code is using MatSim.DINT or something. I have never used the converter myself.

**Comment by JarmoCluyse** [comment]
This is indeed what happens, The type DINT get's replaced by the type MatSim.DINT
the problem is I only write the tooling and I don't have the matlab licence

**Comment by jisotalo** [comment]
Could you provide an example of the matlab-generated PLC code?

**Comment by JarmoCluyse** [comment]
Hi,
we eventually found the issue,
it was a bug in the matlab compiler, this has been fixed in newer versions

**Comment by jisotalo** [comment]
Thank you for confirmation, that's good!
