### ISSUE TITLE
Why is there such an error

### ISSUE THREAD

**Issue by dearthing** [jisotalo/ads-client#113]
Failed to connect x.x.x.x.x.x:801 at startup: ClientException: Connection failed: Device system manager state read failed - ADS error -1 (Timeout - no response in 2000 ms)"

**Comment by crishoj** [comment]
This could result from a missing or misconfigured ADS route, a wrong `targetAmsNetId` in the client, or wrong parameters to `client.connect()`.

Please describe your connection setup — which of the following are you using?

![](https://user-images.githubusercontent.com/13457157/82724547-8dde0800-9cdf-11ea-8dd1-0a1f06f8559f.PNG)

**Comment by jisotalo** [comment]
Closing as there has been no discussion
