### ISSUE TITLE
MBUS card through ADS 

### ISSUE THREAD

**Issue by ptorrent** [jisotalo/ads-client#115]
Hello there !

I've a question about ADS. Is it a way to get data (raw data) from MBUS card  through ADS ?

Thanks for your answer

**Comment by jisotalo** [comment]
If you have a MBUS card KL6781 you probably could read/write the data directly using ADS addresses. However you need to know the protocols.

In the following the terminal would probably be accessed by raw commands at EtherCAT master AmsNetId, port 11, and the indexGroup + indexOffset in picture. However I haven't tested.

![image](https://github.com/jisotalo/ads-client/assets/13457157/0ceda575-6705-43ec-bb9b-1b7e6ac47889)
