### ISSUE TITLE
Add support for BIT data type

### ISSUE THREAD

**Issue by jisotalo** [jisotalo/ads-client#12]
At the moment, BIT type is not supported. Not so trivial to add as the base size at Javascript is byte.

Is it worth doing? Not very used data type.

**Comment by aronneGrinton** [comment]
Hi, I agree with you. Bit type is not very used and also TwinCAT base unit is byte.

**Comment by jisotalo** [comment]
Closing this as it seems that this will not be added. Opening later if it seems to be possible. It could be possible in some pack modes as the offset seems to show bit offset (and then using bitwise operations).
