### ISSUE TITLE
idea: ads-client with Blockly, organization: VisualPLC, problem port 301 without address, 

### ISSUE THREAD

**Issue by runtimevic** [jisotalo/ads-client#121]
Hi,
idea suggestion: 
does this exist ads-client with blockly?
 I think it would be very good,
thanks.

**Comment by jisotalo** [comment]
Could you elaborate more? What do you mean?

**Comment by runtimevic** [comment]
Hi @jisotalo ,
with blocks custom and with node.js and with your library to be able to read and write the variables, and create programs...
https://blockly-demo.appspot.com/static/demos/code/index.html

**Comment by runtimevic** [comment]
Hello @jisotalo , @Hopperpop:

- https://github.com/VisualPLC

- https://www.linkedin.com/posts/v%C3%ADctor-dur%C3%A1n-mu%C3%B1oz-2879a913_merry-christmas-i-am-developing-activity-7143974237270167553-Eq7E?utm_source=share&utm_medium=member_desktop

![VisualPLC](https://github.com/jisotalo/ads-client/assets/53791834/56d68228-fa1f-4c94-abc3-62063a27f3d3)

**Comment by runtimevic** [comment]
Hi @jisotalo , @Hopperpop ,

- adsClient.Connect(301); --> is fault with ads-client...

![TwinCAT_ads-client_port301_error](https://github.com/jisotalo/ads-client/assets/53791834/3c3673bd-8a05-45ca-8aa7-7f974857bbb7)

- program C# not problem is OK
![TwinCAT_C#_Connect_dll](https://github.com/jisotalo/ads-client/assets/53791834/f2a5dc77-0f47-4e0e-86ca-ec4257d3fa12)

How can I send the connection without address, only with port?
thanks Víctor.

**Comment by runtimevic** [comment]
Hello @jisotalo , @Hopperpop 
How can I send the connection without address, only with port 301?
thanks Víctor.

**Comment by jisotalo** [comment]
Sorry @runtimevic , I don't understand what do you mean? If you leave [localAmsNetId](url) empty (or set is as localhost) it will connect to the local runtime.

**Comment by runtimevic** [comment]
Hi @jisotalo 
not work localAmsNetId = localhost
port = 301
![Blockly_TwinCAT_port_301_create_symbols](https://github.com/jisotalo/ads-client/assets/53791834/c74c8c23-15d6-46ba-a22b-1120dc14c6af)
![Blockly_TwinCAT_port_301_log](https://github.com/jisotalo/ads-client/assets/53791834/df48a6dd-f773-4993-9300-9fe83bc14ae8)
![Blockly_TwinCAT_port_301](https://github.com/jisotalo/ads-client/assets/53791834/9e5776cc-527a-4bcb-8db1-06b4224ea597)

**Comment by runtimevic** [comment]
Hi,
I finally solved it:
```javascript
  static async connect(address:string, port:number){
          
    Environment.client = new ads.Client({
      targetAmsNetId: address, //or 'localhost'
      targetAdsPort: port,
      bareClient: true, //NOTE
    })
````

**Comment by Hopperpop** [comment]
The problem is that with default settings it checks if the PLC runtime is running. As you don't have one configured it causes errors.
For that you have the `allowHalfOpen` and `bareClient` option. As i understood `allowHalfOpen` will still checks if it finds the system manager to see if the system is in RUN or CONFIG. With bareClient is also skips that check. (@jisotalo Correct me if I'm wrong.)

**Comment by runtimevic** [comment]
Hi @Hopperpop , @jisotalo 
I solved it this way by adding the bareClient parameter:

![Blockly_TwinCAT_port_301_without_PLC_bareClient](https://github.com/jisotalo/ads-client/assets/53791834/b73bf982-0b8b-4828-bef1-ccc17b7c0743)

If you like the project and want to collaborate in the organization, you are welcome...

- https://github.com/VisualPLC

- https://www.linkedin.com/posts/v%C3%ADctor-dur%C3%A1n-mu%C3%B1oz-2879a913_merry-christmas-i-am-developing-activity-7143974237270167553-Eq7E?utm_source=share&utm_medium=member_desktop

**Comment by jisotalo** [comment]
Good that you solved it!!

@Hopperpop you absolutely right, thanks again!
