### ISSUE TITLE
CX9020

### ISSUE THREAD

**Issue by ptorrent** [jisotalo/ads-client#122]
Hello,

What is the best setting for CX9020 (TwinCAT 2) ?

actually i'm using allowHalfOpen and I got this error in loop:

```
ads-client: WARNING: Connection was lost. Trying to reconnect...
ads-client: PLC runtime reconnected successfully and all subscriptions were restored!
ads-client: WARNING: Connection was lost. Trying to reconnect...
ads-client: PLC runtime reconnected successfully and all subscriptions were restored!
ads-client: WARNING: Connection was lost. Trying to reconnect...
ads-client: PLC runtime reconnected successfully and all subscriptions were restored!
ads-client: WARNING: Connection was lost. Trying to reconnect...
```

Do I've to connect before each read? 

3 time on 4  I got on a read:

```
ClientException: Client is not connected. Use connect() to connect to the target first.
```

But sometimes I got the value

THanks for your support

**Comment by jisotalo** [comment]
Hi!

Could you set the debug level to 3 and paste the console logs (or email them).

One option could be to try with `bareClient` setting instead of `allowHalfOpen`.
