### ISSUE TITLE
ads-client+vite+vanillajs  it's possible?

### ISSUE THREAD

**Issue by runtimevic** [jisotalo/ads-client#125]
Hello, 
I'm trying ads-client+vite+vanillajs
https://github.com/runtimevic/pnpm-vite-vanillajs
package.json:
```
{
  "name": "vite-project",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "devDependencies": {
    "vite": "^5.0.8"
  },
  "dependencies": {
    "ads-client": "^1.14.3"
  }
}
```
![ads-client+vite+vanillajs](https://github.com/jisotalo/ads-client/assets/53791834/e26c6518-f4ce-4f75-bb32-a0020ce27b00)

main.js:
```
import  ads  from 'ads-client';
//const ads = require('ads-client')

const client = new ads.Client({
  targetAmsNetId: '127.0.0.1.1.1',
  targetAdsPort: 851
})

client.connect()
  .then(res => {   
    console.log(`Connected to the ${res.targetAmsNetId}`)
    console.log(`Router assigned us AmsNetId ${res.localAmsNetId} and port ${res.localAdsPort}`)

    return client.disconnect()
  })
  .then(() => {
    console.log('Disconnected')
  })
  .catch(err => {
    console.log('Something failed:', err)
  })

/*
Example console output:

Connected to the 127.0.0.1.1.1
Router assigned us AmsNetId 192.168.1.1.1.1 and port 36837
Disconnected
*/
```

Is this combination vite+vanillajs it's possible?
thanks, Víctor.

**Comment by jisotalo** [comment]
Hi! It's not possible as the ads-client can't run in browser.

**Comment by runtimevic** [comment]
Hi @jisotalo ,
What do you recommend all in one frontend + backend in a single app with javascript or typescript, to put ads-client, blockly, sqlite, mqtt, etc.??

**Comment by benhar-dev** [comment]
Electron

**Comment by runtimevic** [comment]
> Electron

Hi @benhar-dev ,
https://github.com/VisualPLC/Blockly-Electron
help me...

**Comment by jisotalo** [comment]
I'm sorry but this is going a little too off-topic. The technology stack depends on so many things.

I have done few projects using ads-client that use React as frontend and then it communicates to backend using both webosckets and REST api.  And I have also used SQLite, Postgres etc.
