### ISSUE TITLE
Time datatype

### ISSUE THREAD

**Issue by ptorrent** [jisotalo/ads-client#141]
Hello there!

I've an issue reading TIME symbol.always print 4026532152 for 100ms 200ms...

Do you have an idea? Maybe I m not on the last version of the library.  That could be the problem?

Thanks for your support!

**Comment by jisotalo** [comment]
Hi Patrick!

Could you create a simple example with PLC code and Javascript code?

I haven't had issues with TIME so far, so that would help.

**Comment by ptorrent** [comment]
Thanks for your answer ! Seems that on last release it works fine (the release installed has 1-2 year).
