### ISSUE TITLE
Starting/stopping the PLC

### ISSUE THREAD

**Issue by jisotalo** [jisotalo/ads-client#24]
Adding new commands that use ADS Write Control command to start/stop PLC.

- Start PLC runtime
- Stop PLC runtime
- Set system to run mode (if possible)
- Set system to config mode (if possible)

**Comment by MaximeMylle** [comment]
hoping this comes soon :)

**Comment by jisotalo** [comment]
Will look into this after #10 is ready

**Comment by jisotalo** [comment]
Released in 1.5.0. See readme for details:

https://github.com/jisotalo/ads-client#starting-and-stopping-the-plc
https://github.com/jisotalo/ads-client#starting-and-stopping-the-twincat-system

**Comment by MaximeMylle** [comment]
Tested and it works, thanks alot!
