### ISSUE TITLE
How to read/write bit?

### ISSUE THREAD

**Issue by acidos** [jisotalo/ads-client#72]
How can I read/write bit value using index group/offset, hence `readRaw/writeRaw`?

// Thanks for the awesome library, it's precious!

**Comment by jisotalo** [comment]
Hi! If I remember correctly, it's not possible at the moment. 

Instead, would it be possible to convert BIT to BOOL at the PLC and then use the booleans at Node.js?

**Comment by acidos** [comment]
Actually I am trying to read terminal address space, not PLC itself.

**Comment by jisotalo** [comment]
Do you think it's possible to read the whole WORD of the terminal and then check out the bits in the Node.js? I haven't read directly from terminal so just wondering.

**Comment by jisotalo** [comment]
I'm closing this issue for now. It's not possible at the moment.
