### ISSUE TITLE
Writing from PLC to Node Application

### ISSUE THREAD

**Issue by Phil-Davies-Github** [jisotalo/ads-client#98]
Hi, thanks for the library. 

As the node client application has no router attached to it I assume that only read and write from the node client is possible.
Is it possible to read the state of the node client and then write to from the PLC? 

Also do you have the typescript def file you could share please?

Thanks Phil

**Comment by jisotalo** [comment]
If you want to write from PLC to Node.js, you need to run ads-server (https://github.com/jisotalo/ads-server).

This project has no typescript definitions yet. That ads-server project does thought.

**Comment by jisotalo** [comment]
Thanks! 

I'm actually planning to rewrite the library to Typescript someday. Let's see..
