### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by RikMe** [jisotalo/ads-client#99]
PLC: 192.168.11.3
AMSnetID PLC: 5.50.37.33.1.1
Twincat 2

Raspberry Pi : 192.168.11.2

Route has been created on PLC. Settings should be according tot tutorials

Error : "Failed to connect 5.50.37.33.1.1:801 at startup: ClientException: Connection failed: Device system manager state read failed - ADS error -1 (Timeout - no response in 6000 ms)"

![image](https://user-images.githubusercontent.com/44720237/197229022-911db890-c5d1-4a5c-a493-378b78625e62.png)
![image](https://user-images.githubusercontent.com/44720237/197228928-b9b14c95-8b38-4f6f-92ea-59b5102cf51f.png)
![image](https://user-images.githubusercontent.com/44720237/197229276-fc17a17e-481d-4f1a-b452-b4da08723252.png)

**Comment by jisotalo** [comment]
Can you set debugging level to 3 and copy paste the console output here?

**Comment by RikMe** [comment]
![Screenshot 2022-10-25 at 07 29 06](https://user-images.githubusercontent.com/44720237/197690330-0fe31be0-d766-4839-bc2a-f27148b21ab8.png)
![Screenshot 2022-10-25 at 07 29 26](https://user-images.githubusercontent.com/44720237/197690334-d832607a-355d-4f01-b4e0-07165a1d5d4e.png)

**Comment by jisotalo** [comment]
I mean from Node.js side (terminal).

**Comment by RikMe** [comment]
Not quite sure how to pull these up. i'm using the function blocks in NodeRed

**Comment by jisotalo** [comment]
Did you start node-red from a command line or terminal? If yes, then you will see it there.
If not, it's most probably logged somewhere else.

See 
https://stackoverflow.com/questions/39243198/where-to-find-console-in-node-red
https://nodered.org/docs/user-guide/runtime/logging

The latter has a note:
`Note : if you are running as a service on the Raspberry Pi using our install script, you can use the node-red-log command to view the service log.`

**Comment by RikMe** [comment]
![Uploading Screenshot 2022-10-25 at 19.05.42.png…]()

**Comment by RikMe** [comment]
i see targetAdsPort : 1000. Should this not be 801 on TC2 ? is configured as 801 in settings.

**Comment by jisotalo** [comment]
Unfortunately I don't know why it isn't working.  Are you sure that you don't have multiple connections already? See https://github.com/jisotalo/ads-client/issues/47

10000 is the port for system manager so that is correct.

**Comment by jisotalo** [comment]
Any news on this?

**Comment by RikMe** [comment]
No, I tried multiple other settings but no effect I'm afraid.
